server:
  port: 8762
management:
  port: 8763

turbine:
  clusterNameExpression: new String("default")
  appConfig: petclinic-restclient,petclinic-zuul

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/